package burp;

/**
 * Created by fruh on 9/7/16.
 */
public enum ConfigActions {
    A_CREATE_NEW_EXT,
    A_DELETE_SEL_EXT,
    A_DELETE_ALL_EXT,
    A_CREATE_NEW_REP,
    A_DELETE_SEL_REP,
    A_DELETE_ALL_REP,
    A_SEL_CHANGED_EXT,
    A_SEL_CHANGED_REP,
    A_START_STOP_CHANGED,
    A_EXT_CONFIG_CHANGED,
    A_REP_CONFIG_CHANGED,
    A_EXT_VALIDITY,
    A_EXT_FROM_SELECTION,
    A_REP_FROM_SELECTION,
    A_ENABLE_DISABLE,
    A_REVOKE_TOKEN
}
