package burp;

public enum ConfigActions {
	A_EXT_CONFIG_CHANGED,
	A_EXT_VALIDITY,
	A_EXT_ERROR_CONFIG_CHANGED,
	A_EXT_ERROR_VALIDITY,
	A_REP_CONFIG_CHANGED,
	A_REP_VALIDITY,
	A_EXT_COMBO_CONFIG_CHANGED,
	A_EXT_COMBO_CHNAGED_ON_SPOTERROR,
	A_ERROR_CONDITION_CHANGED
}
