package burp;

public enum MenuActions {
	ATOR_ERROR,
	ATOR_MACRO,
	ADD_ITEM,
	FROM_SELECTION,
	ADD_REP_ITEM,
	REP_FROM_SELECTION,
	ADD_EXTRACTION_FOR_REP_ITEM,
	FROM_SELECTION_EXTRACTION_FOR_REP,
	A_ENABLE_DISABLE,
	EXPORT_CONFIG,
	IMPORT_CONFIG
}
